name: "Create Kubernetes Status Badge"
description: "Create a status badge for your Kubernetes cluster"
inputs:
  kubeconfig-path:
    description: "Path to kubeconfig file"
    required: true
outputs:
  time:
    description: "The time we greeted you"
runs:
  using: "node20"
  main: "index.js"
