name: "Create Kubernetes Status Badge"
description: "Create a status badge for your Kubernetes cluster"
inputs:
  kubeconfig:
    description: "kubeconfig text"
    required: true
  k8sStatus-SVG-text:
    description: "Text to display on the k8s SVG"
    default: "Kubernetes Status"
  podStatus-SVG-text:
    description: "Text to display on the pod SVG"
    default: "Healthy Pods"
  nodeStatus-SVG-text:
    description: "Text to display on the node SVG"
    default: "Healthy Nodes"
outputs:
  k8sStatus-SVG-Path:
    description: "Path to the generated SVG file"
    value: ${{ steps.svg-gen.outputs.k8sStatus-SVG-Path }}
  podStatus-SVG-Path:
    description: "Path to the generated SVG file"
    value: ${{ steps.svg-gen.outputs.podStatus-SVG-Path }}
  nodeStatus-SVG-Path:
    description: "Path to the generated SVG file"
    value: ${{ steps.svg-gen.outputs.nodeStatus-SVG-Path }}
runs:
  using: "composite"
  steps:
    - id: checkout
      uses: actions/checkout@v3
      with:
        repository: walnuts1018/k8s-badge

    - uses: actions/setup-node@v3
      with:
        node-version: 20

    - run: npm install
      shell: bash

    - id: svg-gen
      run: node index.js
      shell: bash
      env:
        KUBE_CONFIG: ${{ inputs.kubeconfig }}
        K8S_STATUS_SVG_TEXT: ${{ inputs.k8sStatus-SVG-text }}
        POD_STATUS_SVG_TEXT: ${{ inputs.podStatus-SVG-text }}
        NODE_STATUS_SVG_TEXT: ${{ inputs.nodeStatus-SVG-text }}

    - name: determine username and repository name
      id: repo-info
      run: |
        echo "::set-output name=username::$(echo ${GITHUB_REPOSITORY} | cut -d '/' -f 1)"
        echo "::set-output name=reponame::$(echo ${GITHUB_REPOSITORY} | cut -d '/' -f 2)"
      shell: bash

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public

branding:
  icon: "user"
  color: "blue"
